### ISSUE TITLE
Access to clipboard

### ISSUE THREAD

**Issue by Fastidious** [lus/pasty#35]
I am getting "Clipboard permission denied" when clicking on the clipboard icon. Happening on macOS 12.1, under Safari 15.2 (17612.3.6.1.6).

**Comment by lus** [comment]
I hate browsers.
I'll fix it later this evening.

**Comment by Fastidious** [comment]
I forgot to specify that I am running from the `develop` branch. Apologies about the omission.

**Comment by lus** [comment]
No worries, the corresponding code should be equal on both branches anyway.
Thank you for reporting!

**Comment by lus** [comment]
I could reproduce the error on my iPad and found out that it occurs because Safari does not support the Permissions API which was used to ask for `clipboard-write` permissions.
This permission check however is redundant as the `clipboard-write` permission automatically is granted for active tabs, so I completely removed it.
Another check using my iPad succeeded. I will redeploy the public instance in the next few minutes, please let me know if the issue is fixed for you.
Remember that you may need to hard-refresh the tab where you opened pasty in order to refresh your browser cache.

**Comment by Fastidious** [comment]
Worked perfectly. Thanks for the quick fix!
